name: hello-world
on: push
jobs:
  github-actions-training:
    name: GitHub Actions Training
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone the Repo
        uses: actions/checkout@v3
      - name: Building App
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Testing App
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Uploading Repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
